# NumPy documentation

Please refer: https://numpy.org/devdocs/user/


# Note:

1. *If there are any errors in your code you will not receive more than 50% of the points for that question. Please test your code thoroughly before submission.*

2. *The submitted file must be a Jupyter Notebook with the correct* **.ipynb** *extension. Ensure that the notebook is properly named and includes all necessary code and outputs.* **Submissions in any other format will receive a score of 0.**
 
 
 # Submission:
    Please rename your notebook as <your_name>_Lab02.ipynb and submit on Canvas

# Grading Summary (Total: 25 Points):

**The submitted file name is as mentioned above: 1 Point**

**Descriptive identifiers are used: 3 Points**

**Outputs are displayed with appropriate messages: 3 Points**

**Q1: 4 Points**

**Q2: 4 Points**

**Q3: 10 Points**

**Q1:**

1. Create a 1D NumPy array with numbers from 5 to 100 in steps of 5. Calculate the sum, mean, and the standard deviation of the array.
2. Extract all elements in the array that are divisible by both 3 and 5.

In [34]:
import numpy as np

five_array = np.arange(5, 101, 5)
five_array

divisibly_by_5 = five_array % 5 == 0
divisible_by_3 = five_array % 3 == 0

d5_array = five_array[divisibly_by_5]
d5_d3_array = d5_array[divisible_by_3]

print("These numbers are divisible by both 3 and 5", d5_d3_array)


These numbers are divisible by both 3 and 5 [15 30 45 60 75 90]


**Q2:**

1. Create a 5x5 matrix of integers ranging from 1 to 25. Replace the diagonal elements with -1.
2. Create a 4x3 matrix of random integers between 20 and 60. Extract all elements from the first and last rows.


In [53]:
matrix = np.arange(1, 26).reshape(5, 5)
np.fill_diagonal(matrix, -1)
matrix

array([[-1,  2,  3,  4,  5],
       [ 6, -1,  8,  9, 10],
       [11, 12, -1, 14, 15],
       [16, 17, 18, -1, 20],
       [21, 22, 23, 24, -1]])

In [93]:
matrix_4 = np.random.randint(20, 60, size=(4, 3))
first_row = matrix_4[0]
last_row = matrix_4[-1]
print("the matrix :")
print(matrix_4)
print("elements from the first row", first_row)
print("elements from the last row", last_row)



the matrix :
[[43 43 47]
 [59 26 39]
 [51 52 44]
 [38 55 56]]
elements from the first row [43 43 47]
elements from the last row [38 55 56]


# Q3:

You are given a 2D NumPy array representing the monthly sales (in dollars) of different products in a store over 6 months. 
Each row corresponds to a product, and each column corresponds to a month.

1. Find the product with the highest total sales.
2. Find months where Product 3 had sales greater than 2100 dollars.

In [95]:
import numpy as np

data = np.array([["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    [1200, 1500, 1700, 1600, 1800, 1900],  # Product 1
    [1000, 1100, 1050, 1300, 1250, 1400],  # Product 2
    [2000, 1950, 2100, 2200, 2300, 2250],  # Product 3
    [900, 950, 980, 1000, 1100, 1200],     # Product 4
    [1700, 1800, 1850, 1900, 1950, 2000]   # Product 5
])


months = data[0,:]
sales_data = data[1:,].astype(int)

In [129]:
highest_sale = np.max(sales_data)
print("product 3 has the highest sale of", highest_sale)


product 3 has the highest sale of 2300


In [140]:
product3_row = sales_data[2, :]
highest_months = months[product3_row > 2100]
print("Product 3 had sales greater than 2100 in the following months: ", highest_months)


Product 3 had sales greater than 2100 in the following months:  ['Apr' 'May' 'Jun']
